---
- name: Getting Remote IPv4
  set_fact:
    remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Installing prerequisites for OSSEC
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - inotify-tools
    - wget
    - python-pip
    - python3-pip
    - build-essential
    - make
    - unzip
  
- name: Python Dependencies
  command: pip install pexpect

- name: Downloading OSSEC v2.9.3
  unarchive:
    src: https://github.com/ossec/ossec-hids/archive/2.9.3.tar.gz
    dest: /opt/
    remote_src: yes

- name: Installing OSSEC-HIDS in local mode
  expect:
    command: "/bin/bash /opt/ossec-hids-2.9.3/install.sh"
    timeout: 300
    responses:
      en/br: "en"
      Press ENTER: ""
      What kind of installation do you want: "{{ ossec_install_type }}"
      Choose where to install the OSSEC HIDS: "{{ ossec_dir }}"
      Do you want e-mail notification: "{{ ossec_email }}"
      Do you want to run the integrity check daemon: "{{ ossec_integritycheck_daemon }}"
      Do you want to run the rootkit detection engine: "{{ ossec_rootkit_engine }}"
      Do you want to enable active response: "{{ ossec_active_response }}"
      Do you want to enable the firewall-drop response: "{{ ossec_firewalldrop_response }}"
      Do you want to add more IPs to the white list: "n"
  become: yes
  notify: restart ossec
  register: ossecinstall

- name: Starting OSSEC service
  service:
    name: ossec
    state: started

- name: Configuringing OSSEC
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf

- name: Enabling client-syslog service
  command: "/var/ossec/bin/ossec-control enable client-syslog"
  
- name: Restarting Ossec
  command: "/var/ossec/bin/ossec-control restart"

